- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/wizards/templates/NewProjectPage.java
At least on my standard Ubuntu/GTK installation, one line from the
package edit text help text is missing. Therefore give it some more
space.
> New project wizard package description is cut

- andmore-core/plugins/certmanager/plugin.xml
- android-core/plugins/org.eclipse.andmore.package/.classpath
Not sure why they don't happen in others. An object contribution
attribute, objectClass, was spelled with the missing camel case.
Also in andmore.package, the src source folder doesn't exist so I
removed it.
Signed-off-by: Doug Schaefer <dschaefer@qnx.com>
> Fix build errors in my environment.

- README.md
Updated the README.md so that it has a link back to the
project homepage.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=459407
> [459407] Update README.md with link to project homepage

- README.md
Fixed a few typos.  Updated the build instructions based on my experiences with importing
into an Eclipse workspace.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=bugnumber
Signed-off-by: Eric Cloninger <ericc@pobox.com>
> [nobug] Update README.md for Eclipse build instructions

- android-core/plugins/org.eclipse.andmore.integration.tests/unittests/org/eclipse/andmore/internal/editors/layout/gle2/SwtUtilsTest.java
Sometimes the swtutils test will fail under linux but
not on other platforms.  To get around this, use
assumeThat assertion to have the test marked as skipped
if it does fail.
> [nobug] SwtUtils sometimes fails under linux

- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/core/internal/CollectLogFile.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/core/internal/EclipseLogFile.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/core/internal/EnvironmentLogFile.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/core/internal/StudioLogFile.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/ui/LogFileColumn.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/ui/handler/LoggerCollectorHandler.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/ui/wizard/LoggerCollectorWizard.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/ui/wizard/LoggerCollectorWizardPage.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/util/LogCollectorExtensionLoader.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/util/LoggerCollectorConstants.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/util/LoggerCollectorMessages.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/util/PlatformException.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/util/PlatformLogger.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/util/WidgetsFactory.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/util/WidgetsUtil.java
- andmore-core/plugins/logger.collector/src/org/eclipse/andmore/android/logger/collector/util/ZipUtil.java
Log collector packages neede to be renamed to
the org.eclipse.andmore namespace.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=457343
> [457343] Rename log collector packages

- README.md
- andmore-core/plugins/common/about.properties
- android-core/plugins/org.eclipse.andmore.ddms/about.properties
- android-core/plugins/org.eclipse.andmore.ndk/about.properties
- android-core/plugins/org.eclipse.andmore.package/about.properties
- android-core/plugins/org.eclipse.andmore.traceview/about.properties
- android-core/plugins/org.eclipse.andmore/about.properties
Acknowledging the provenance of the green robot used in some images and the CC terms
under which it is used.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=461075
Signed-off-by: Eric Cloninger <ericc@pobox.com>
> Bring in robot provenance commits

- android-core/plugins/org.eclipse.andmore.integration.tests/pom.xml
A new profile "skipTests" can be enabled.  This will
skip the integration tests during a build.
> [nobug] Set a build profile to skip tests

- android-core/plugins/org.eclipse.andmore/META-INF/MANIFEST.MF
- android-core/plugins/org.eclipse.andmore/andmore.target
The AOSP lint check tool requires that we use ObjectWeb ASM 4.0.
Any other version will cause NoClassDefFound errors to occur and
the build to lock.   This change makes sure the target platform
has 4.0 available to it, and also makes sure the plugin that
requires this excludes versions below 4.0 and 5.0.  We can't
use higher versions due to breaking API changes.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=461459
> [461459] Restrict version of ObjectWeb Dependency

- andmore-core/plugins/emulator/src/org/eclipse/andmore/android/emulator/device/instance/AndroidDevInstListener.java
- andmore-core/plugins/emulator/src/org/eclipse/andmore/android/emulator/ui/view/AbstractAndroidView.java
Emulator view is being removed, so delete the code that
caused it pop up.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=461547
> [461547] Do not prompt to open Emulator View

- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/AndmoreAndroidConstants.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/project/ProjectHelper.java
The default is to use Java 1.7, but we allow Java 1.8 per user
request for some tools that can backport lambdas.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=461334
> [461334] Allow users to select and use Java 1.8.

- android-core/plugins/org.eclipse.andmore.gldebugger/src/org/eclipse/andmore/gltrace/DeviceViewAction.java
- android-core/plugins/org.eclipse.andmore.integration.tests/src/org/eclipse/andmore/integration/tests/DefaultDialogProcessor.java
- android-core/plugins/org.eclipse.andmore.integration.tests/src/org/eclipse/andmore/integration/tests/DialogMonitor.java
- android-core/plugins/org.eclipse.andmore.integration.tests/src/org/eclipse/andmore/integration/tests/DialogMonitorJob.java
- android-core/plugins/org.eclipse.andmore.integration.tests/src/org/eclipse/andmore/integration/tests/IDialogProcessor.java
- android-core/plugins/org.eclipse.andmore.integration.tests/src/org/eclipse/andmore/integration/tests/IntegrationTestSuite.java
- android-core/plugins/org.eclipse.andmore.integration.tests/src/org/eclipse/andmore/integration/tests/UnitTestHelper.java
- android-core/plugins/org.eclipse.andmore.ndk/discovery/test.c
- android-core/plugins/org.eclipse.andmore.ndk/discovery/test.cpp
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/Messages.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/build/Messages.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/editors/layout/gle2/ShowWithinMenu.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/editors/layout/gle2/SubmenuAction.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/editors/ui/ErrorImageComposite.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/preferences/Messages.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/wizards/templates/TypedVariable.java
Several files were missing appropriate copyright headers.
Most of these were from the original ADT project and were
missing when they were forked.  For consistency I have added
the basic headers back in.
Any new files that are created are licensed under the EPL
by the person creating the file.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=461960
> [461960] Several files were missing copyright headers

- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/preferences/AndroidPreferencePage.java
SdkStatsService can popup a dialog the first time it is called
if the Android SDK location has not been specified.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=462184
> [462184] Remove call to SdkStatsService

- android-core/features/org.eclipse.andmore/feature.xml
Include the objectweb dependency in the feature so that
third parties do not need to add eclipse orbit to their
build.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=460134
> [460134] Include object web dependency in feature

- README.md
Added documentation around the location where the nightly p2
site.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=460134
> [460134] Add documentation for Nightly P2 site

- andmore-core/plugins/android.codeutils/plugin.xml
The plugin.xml commands were referencing the wrong class package
names, thus causing the wizards not to launch.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=456970
> [456970] Fix Wizards so they launch

- android-core/plugins/org.eclipse.andmore/plugin.xml
Due to a mis-named category name the Android category was lost.
This fixes the category name so it is spelled correctly.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=461460
> [461460] Fix Android Import Category

- andmore-core/plugins/android/plugin.properties
- andmore-core/plugins/android/plugin.xml
- andmore-core/plugins/android/src/org/eclipse/andmore/android/command/ConvertADTProject.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/AndmoreAndroidConstants.java
A simple command that takes a list of projects selected from the
UI and converts them to use the Andmore nature and Builder ids.
This is a work in progress.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=463598
> [463598] Convert ADT Projects to work with Andmore

- andmore-core/features/basic/feature.properties
- andmore-core/features/feature/feature.properties
- android-core/features/org.eclipse.andmore.gldebugger/feature.xml
- android-core/features/org.eclipse.andmore.hierarchyviewer/feature.xml
- android-core/features/org.eclipse.andmore.ndk/feature.xml
- android-core/features/org.eclipse.andmore.package/feature.xml
- android-core/features/org.eclipse.andmore.traceview/feature.xml
- android-core/features/org.eclipse.andmore/feature.xml
Per eclipse incubating project guidelines all features provided
need to clearly indicate that they are incubating while still
in the incubation phase.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=463893
> [463893] Label all features as Incubating

- android-core/plugins/org.eclipse.andmore.ddms/src/org/eclipse/andmore/ddms/DdmsPlugin.java
- android-core/plugins/org.eclipse.andmore.ddms/src/org/eclipse/andmore/ddms/LogCatMonitorDialog.java
- android-core/plugins/org.eclipse.andmore/.settings/org.moreunit.prefs
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/AndmoreAndroidConstants.java
There are cases where \n is not working as expected, use the system
defined NEWLINE provided by the java runtime.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=463916
> [463916] Add platform independent NEWLINE constant

- android-core/plugins/org.eclipse.andmore/plugin.xml
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=471901
Signed-off-by: Kaloyan Raev <kaloyan.r@zend.com>
> [471901] Android Common XML Editor should not be the default

- andmore-core/plugins/db.devices/META-INF/MANIFEST.MF
- andmore-core/plugins/db.devices/src/org/eclipse/andmore/android/db/devices/model/ApplicationNode.java
An NPE would be thrown when trying to show the icon for an application
in the database explorer for the Android Database perspective.
The dependency was missing and the wrong value was hard coded.  Plugin
now uses the correct Constant value instead of a magic value.  So if the
constant value changes this will be picked up automatically.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=468473
> [468473] NPE when expanding application node in db explorer

- andmore-core/plugins/android/META-INF/MANIFEST.MF
- andmore-core/plugins/android/files/main-dex-list.txt
- andmore-core/plugins/android/src/org/eclipse/andmore/android/i18n/AndroidNLS.java
- andmore-core/plugins/android/src/org/eclipse/andmore/android/i18n/androidNLS.properties
- andmore-core/plugins/android/src/org/eclipse/andmore/android/multidex/MultiDexManager.java
- andmore-core/plugins/android/src/org/eclipse/andmore/android/propertypage/AndmorePropertyPage.java
- android-core/plugins/org.eclipse.andmore.integration.tests/META-INF/MANIFEST.MF
- android-core/plugins/org.eclipse.andmore.integration.tests/src/org/eclipse/andmore/integration/tests/IntegrationTestSuite.java
- android-core/plugins/org.eclipse.andmore.integration.tests/src/org/eclipse/andmore/internal/build/DexWrapperTest.java
- android-core/plugins/org.eclipse.andmore.integration.tests/src/org/eclipse/andmore/internal/settings/MultiDexTest.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/build/BuildHelper.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/build/DexWrapper.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/build/builders/PostCompilerBuilder.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/project/ExportHelper.java
Signed-off-by: Thys ten Veldhuis <t.tenveldhuis@gmail.com>
Added basic support for multi-dex. You can enable it by going to 
*Project > Properties > Android > General* and enabling the 'Enable MultiDex support' checkbox. This then adds two properties to the project.properties file:
> multidex.enabled=true
> multidex.main-dex-list=main-dex-list.txt
Enabling the checkbox also copies the *main-dex-list.txt* file so the user can specify which classes to include in the classes.dex which is automatically loaded before `MultiDex.install` is executed.
> [476446] MultiDex support for Android APK

- andmore-core/plugins/android.macosx/pom.xml
- android-core/plugins/org.eclipse.andmore/andmore.target
- pom.xml
Needed to remove the Mac OSX 32 bit support as that is no longer supported by Mars and the eclipse platform.
> Update the build to use MARS and tycho 0.23.1

- .project
- pom.xml
The parent pom.xml is updated to support JAR signing and deployment to
Nexus. Tycho is updated to the latest 0.24.0 version.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=459574
Signed-off-by: Kaloyan Raev <kaloyan.r@zend.com>
> [459574] Migrate Build to use the CBI

- andmore-core/plugins/certmanager/src/org/eclipse/andmore/android/certmanager/packaging/sign/PackageFileSigner.java
- andmore-core/plugins/certmanager/src/org/eclipse/andmore/android/certmanager/packaging/sign/SignatureBlockFile.java
The code for generating the signature block file (CERT.RSA) was
commented and not executed. It used sun.security.pkcs.* classes. This
code is now re-implemented using Bounty Castle.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=484461
Signed-off-by: Kaloyan Raev <kaloyan.r@zend.com>
> [484461] APK signing is broken

- android-core/plugins/org.eclipse.andmore.ddms/src/org/eclipse/andmore/ddms/i18n/Messages.java
- android-core/plugins/org.eclipse.andmore.ddms/src/org/eclipse/andmore/ddms/i18n/messages.properties
- android-core/plugins/org.eclipse.andmore.ddms/src/org/eclipse/andmore/ddms/preferences/PreferencePage.java
I discovered that launching a second instance of Eclipse with Andmore installed would fail, this adds a pref page entry to configure the port to avoid duplication.
> Add pref page entry for PreferenceInitializer.ATTR_SELECTED_DEBUG_PORT

- android-core/plugins/org.eclipse.andmore.ndk/META-INF/MANIFEST.MF
The @Override statments that refer to interfaces require at least 1.6 as
execution environment. This change sets the missing require statement in
the plugin manifest.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=509683
Signed-off-by: Marcus Handte <handte@locoslab.com>
> [509683] Set execution environment in NDK plugin manifest.

- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/build/BuildHelper.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/properties/AndroidPropertyPage.java
- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/sdk/ProjectState.java
Setting --no-version-vectors is necessary when using newer versions
(e.g. 25.1.0) of the appcompat library to target older Android devices.
If this flag is not set during the packaging, older devices will not be
able to access Android resource files properly. This results in app
crashes upon startup due to seemingly missing resources.
This commit extends the andmore user interface to include a check box in
the project-specific Android properties page which enables the user to
add the --no-version-vectors option during aapt runs. The value of the
check box is stored in the project.properties file and picked up by the
build helper when running aapt. If the properties file does not contain
the new property, the default is to not add the option during builds in
order to avoid side effects.
> [509663] Add support for aapt --no-version-vectors option.

- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/build/builders/BaseBuilder.java
When a project does not contain a project.poperties file, the
BaseBuilder will run into a NullPointerException. This change will
prevent the exception and abort the build. 
Note that this does not fix the new project wizard problem that is the
root cause of having an invalid project setup in the first place.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=484566
Signed-off-by: Marcus Handte <handte@locoslab.com>
> [484566] Fix NPE in BaseBuilder when property file is missing.

- android-core/plugins/org.eclipse.andmore/src/org/eclipse/andmore/internal/editors/layout/configuration/ConfigurationMatcher.java
When a project contains locales without region, the visual editor will fail to load due to a NPE in the algorithm that guesses the best default locale. As a result, the user will get a "no root view" message.
This change modifies the selection algorithm of the ConfigurationMatcher to either return a full language and region match or to return the last matching language setting without causing a NPE when the region is null. 
The only side effect I can see is that it will fully traverse the list if there is no full match instead of aborting earlier.  However, my feeling is that the resulting "loss of performance" is not noticeable whereas the NPE clearly is.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=509666
Signed-off-by: Marcus Handte handte@locoslab.com
> [509666] Fix NPE in visual editor that causes load failures.
